import type {
  Attack,
  Finding,
  GraphEdge,
  GraphNode,
  NodeDetail,
} from "@/types/ThreatModel";

export const PROVIDERS: { value: string; text: string }[] = [
  { value: "crewai", text: "CrewAI" },
  { value: "dify", text: "Dify" },
  { value: "langgraph", text: "LangGraph" },
  { value: "generic", text: "Generic (explicit nodes/edges)" },
  { value: "n8n", text: "n8n" },
];

export const YAML_COUNT: Record<string, number> = {
  crewai: 2,
  dify: 1,
  langgraph: 1,
  generic: 1,
  n8n: 1,
};

// Cosmetic reasoning lines for the parse stage (Processing step). The rule
// engine runs later, on the way to Results, so these describe parsing and
// capability extraction only — not risk paths / rule execution / scoring.
export const REASONING: string[] = [
  "Loading agent definition…",
  "Normalizing to IR v1.2…",
  "Detecting framework…",
  "Building capability graph (NetworkX)…",
  "Detecting untrusted input nodes…",
  "Detecting sensitive read capabilities…",
  "Detecting external output nodes…",
  "Extracting agent capabilities…",
  "Capability extraction complete",
];

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "FH-001",
    ruleId: "FH-001",
    severity: "critical",
    category: "capability_path",
    title: "Full PII exfiltration: untrusted input → sensitive read → external output",
    desc: "Attacker controls web form → screener reads ATS DB (PII, GDPR) → communicator emails externally without HITL.",
    path: ["WebForm", "AppIntake", "Screener", "ATSQuery", "ATS DB", "Communicator", "GmailSend", "Email"],
    edges: ["edge_001", "edge_002", "edge_006", "edge_011", "edge_015", "edge_016", "edge_009", "edge_017"],
    score: 9.8,
    evidence: {
      input_trust_level: "untrusted",
      data_sensitivity: "critical",
      sensitive_assets: ["ATS Database", "CV Attachments"],
      output_boundary: "external",
      approval_gate_present: false,
      agent_count: 3,
    },
    owaspAgentic: ["T6"],
    owaspLlm: ["LLM06"],
    mitre: ["AML.T0054", "AML.T0048"],
    controls: ["humanInTheLoop", "outputFiltering", "piiRedaction", "leastPrivilege"],
    findingClass: "attack",
  },
  {
    id: "FH-006",
    ruleId: "FH-006",
    severity: "critical",
    category: "capability_path",
    title: "Indirect injection via LinkedInFetch with lateral propagation",
    desc: "LinkedIn profiles are untrusted external content. Malicious payload flows to Screener agent without contentValidation.",
    path: ["LinkedInFetch", "LinkedIn Profiles", "Screener"],
    edges: ["edge_007", "edge_012"],
    score: 9.1,
    evidence: {
      input_trust_level: "untrusted",
      fetch_web_external: true,
      content_validation_present: false,
      agent_count: 2,
      output_boundary: "external",
      approval_gate_present: false,
    },
    owaspAgentic: ["T5"],
    owaspLlm: ["LLM01"],
    mitre: ["AML.T0051"],
    controls: ["contentValidation", "urlAllowlist", "humanInTheLoop"],
    findingClass: "attack",
  },
  {
    id: "FH-011",
    ruleId: "FH-011",
    severity: "critical",
    category: "missing_control",
    title: "Irreversible calendar modification from untrusted source",
    desc: "Web form input delegated to Interview Scheduler which writes to Hiring Calendars without HITL approval.",
    path: ["AppIntake", "InterviewScheduler", "CalendarWrite", "Hiring Calendars"],
    edges: ["edge_003", "edge_008", "edge_013"],
    score: 8.6,
    evidence: {
      output_boundary: "internal",
      side_effect: true,
      side_effect_reversible: false,
      approval_gate_present: false,
      agent_count: 2,
    },
    owaspAgentic: ["T6"],
    owaspLlm: ["LLM08"],
    mitre: ["AML.T0040"],
    controls: ["humanInTheLoop", "dryRunFirst", "rollbackReady"],
    findingClass: "attack",
  },
  {
    id: "FH-013",
    ruleId: "FH-013",
    severity: "high",
    category: "trust_boundary_violation",
    title: "PII leak to external channel from candidate data",
    desc: "Candidate PII can reach external email channels. piiRedaction and outputFiltering both absent.",
    path: ["Screener", "Communicator", "GmailSend"],
    edges: ["edge_016", "edge_009"],
    score: 8.2,
    evidence: {
      data_sensitivity: "high",
      output_boundary: "external",
      approval_gate_present: false,
      pii_redaction_present: false,
      agent_count: 2,
    },
    owaspAgentic: ["T6"],
    owaspLlm: ["LLM06"],
    mitre: ["AML.T0054"],
    controls: ["piiRedaction", "outputFiltering"],
    findingClass: "attack",
  },
  {
    id: "FH-007",
    ruleId: "FH-007",
    severity: "high",
    category: "missing_control",
    title: "5-agent chain with no intermediate controls",
    desc: "Full delegation chain from untrusted input to external output with only perimeter controls present.",
    path: ["AppIntake", "Screener", "cvParser", "Scheduler", "Communicator"],
    edges: [],
    score: 8.0,
    evidence: {
      agent_count: 5,
      controls_on_path: 0,
      output_boundary: "external",
    },
    owaspAgentic: ["T6", "T5"],
    owaspLlm: ["LLM06", "LLM01"],
    mitre: ["AML.T0054"],
    controls: ["delegationScoping", "interAgentAuthentication"],
    findingClass: "attack",
  },
];

export const RESULTS_SUMMARY = {
  agents: 5,
  tools: 5,
  dataAssets: 4,
  findingsTotal: 15,
  criticalTotal: 3,
  highTotal: 2,
  mediumTotal: 6,
  lowTotal: 4,
  maxScore: 9.8,
};

export const G_NODES: GraphNode[] = [
  { id: "n0", type: "input", label: "Web Form\n(Public)", sub: "trust: untrusted", x: 68, y: 295, riskScore: 9.8, badges: ["untrusted"] },
  { id: "n1", type: "agent", label: "Application\nIntake", sub: "role: coordinator", x: 238, y: 295, riskScore: 9.8, badges: ["full_auto"] },
  { id: "n2", type: "agent", label: "Candidate\nScreener", sub: "read+fetchWeb+decide", x: 440, y: 295, riskScore: 9.8, badges: ["full_auto", "no_guardrails"] },
  { id: "n3", type: "agent", label: "cvParser", sub: "GPT-4o-mini", x: 352, y: 143, riskScore: 0, badges: ["full_auto", "no_guardrails"] },
  { id: "n4", type: "agent", label: "Interview\nScheduler", sub: "autonomy: full_auto", x: 378, y: 473, riskScore: 8.6, badges: ["full_auto"] },
  { id: "n5", type: "agent", label: "Candidate\nCommunicator", sub: "autonomy: full_auto", x: 1052, y: 295, riskScore: 9.8, badges: ["full_auto"] },
  { id: "n6", type: "tool", label: "PDFParser", sub: "capability: read", x: 618, y: 143, riskScore: 0, badges: ["no_approval"] },
  { id: "n7", type: "tool", label: "ATSQuery", sub: "capability: read", x: 618, y: 253, riskScore: 9.8, badges: ["no_approval"] },
  { id: "n8", type: "tool", label: "LinkedInFetch", sub: "capability: fetchWeb", x: 618, y: 373, riskScore: 9.1, badges: ["no_approval"] },
  { id: "n9", type: "tool", label: "CalendarWrite", sub: "capability: modify", x: 618, y: 487, riskScore: 8.6, badges: ["side_effect", "no_approval"] },
  { id: "n10", type: "tool", label: "GmailSend", sub: "capability: send", x: 1148, y: 295, riskScore: 9.8, badges: ["side_effect", "no_approval"] },
  { id: "n11", type: "data", label: "CV Attachments", sub: "sensitivity: HIGH·PII", x: 822, y: 143, risk: "high", riskScore: 0, badges: ["high_sensitivity", "pii"] },
  { id: "n12", type: "data", label: "ATS Database", sub: "HIGH·PII·GDPR", x: 822, y: 253, risk: "high", riskScore: 9.8, badges: ["high_sensitivity", "pii"] },
  { id: "n13", type: "data", label: "LinkedIn Profiles", sub: "UNTRUSTED·external", x: 822, y: 373, risk: "medium", riskScore: 9.1, badges: [] },
  { id: "n14", type: "data", label: "Hiring Calendars", sub: "MEDIUM·internal", x: 822, y: 487, risk: "medium", riskScore: 8.6, badges: [] },
  { id: "n15", type: "output", label: "Email to\nCandidate", sub: "boundary: external", x: 1328, y: 295, riskScore: 9.8, badges: ["external", "no_approval_gate"] },
  { id: "c1", type: "control", label: "inputSan.", status: "present", x: 152, y: 295, riskScore: 0, badges: [] },
  { id: "c2", type: "control", label: "delegation\nScoping", status: "present", x: 338, y: 295, riskScore: 0, badges: [] },
  { id: "c3", type: "control", label: "humanIn\nTheLoop", status: "absent", x: 1242, y: 295, riskScore: 9.8, badges: [] },
  { id: "c4", type: "control", label: "content\nValidation", status: "absent", x: 725, y: 373, riskScore: 9.1, badges: [] },
];

export const G_EDGES: GraphEdge[] = [
  { id: "edge_001", f: "n0", t: "n1", lbl: "", capability: "receiveInstruction", riskLevel: "critical", blocked: false, findingIds: ["FH-001"] },
  { id: "edge_002", f: "n1", t: "n2", lbl: "delegateTo", capability: "delegateTo", type: "delegate", riskLevel: "critical", blocked: false, findingIds: ["FH-001"] },
  { id: "edge_003", f: "n1", t: "n4", lbl: "delegateTo", capability: "delegateTo", type: "delegate2", cx: 250, cy: 475, riskLevel: "critical", blocked: false, findingIds: ["FH-011"] },
  { id: "edge_004", f: "n2", t: "n3", lbl: "delegateTo", capability: "delegateTo", type: "delegate", cx: 340, cy: 143, riskLevel: "none", blocked: false, findingIds: [] },
  { id: "edge_005", f: "n2", t: "n6", lbl: "usa", capability: "invokeTool", riskLevel: "none", blocked: false, findingIds: [] },
  { id: "edge_006", f: "n2", t: "n7", lbl: "usa", capability: "invokeTool", riskLevel: "critical", blocked: false, findingIds: ["FH-001"] },
  { id: "edge_007", f: "n2", t: "n8", lbl: "fetchWeb", capability: "fetchWeb", cx: 520, cy: 373, riskLevel: "critical", blocked: false, findingIds: ["FH-006"] },
  { id: "edge_008", f: "n4", t: "n9", lbl: "usa", capability: "invokeTool", riskLevel: "critical", blocked: false, findingIds: ["FH-011"] },
  { id: "edge_009", f: "n5", t: "n10", lbl: "usa", capability: "invokeTool", riskLevel: "critical", blocked: false, findingIds: ["FH-001", "FH-013"] },
  { id: "edge_010", f: "n6", t: "n11", lbl: "lee", capability: "read", riskLevel: "none", blocked: false, findingIds: [] },
  { id: "edge_011", f: "n7", t: "n12", lbl: "lee", capability: "read", riskLevel: "critical", blocked: false, findingIds: ["FH-001"] },
  { id: "edge_012", f: "n8", t: "n13", lbl: "lee", capability: "read", riskLevel: "critical", blocked: false, findingIds: ["FH-006"] },
  { id: "edge_013", f: "n9", t: "n14", lbl: "escribe", capability: "modifyResource", riskLevel: "critical", blocked: false, findingIds: ["FH-011"] },
  { id: "edge_014", f: "n11", t: "n2", lbl: "dataFlow", capability: "dataFlow", type: "return", cx: 680, cy: 60, riskLevel: "none", blocked: false, findingIds: [] },
  { id: "edge_015", f: "n12", t: "n2", lbl: "dataFlow", capability: "dataFlow", type: "return", cx: 680, cy: 50, riskLevel: "critical", blocked: false, findingIds: ["FH-001"] },
  { id: "edge_016", f: "n2", t: "n5", lbl: "", capability: "delegateTo", riskLevel: "critical", blocked: false, findingIds: ["FH-001", "FH-013"] },
  { id: "edge_017", f: "n10", t: "n15", lbl: "", capability: "send", riskLevel: "critical", blocked: false, findingIds: ["FH-001"] },
];

export const ATTACKS: Attack[] = [
  { id: "FH-001", severity: "critical", width: 2.5, nodes: ["n0", "n1", "n2", "n7", "n12"], label: "FH-001", dash: false },
  { id: "FH-001b", severity: "critical", width: 2.5, nodes: ["n12", "n2", "n5", "n10", "n15"], label: "", dash: false },
  { id: "FH-006", severity: "critical", width: 2.5, nodes: ["n8", "n13"], label: "FH-006", dash: false },
  { id: "FH-006b", severity: "critical", width: 2, nodes: ["n13", "n2"], label: "", dash: true, cx: 700, cy: 500 },
  { id: "FH-011", severity: "high", width: 2.5, nodes: ["n1", "n4", "n9", "n14"], label: "FH-011", dash: false },
];

export const NODE_PROPS: Record<string, NodeDetail> = {
  n0: {
    description: "Public-facing web form accepting job applications. All content is untrusted and may carry injected payloads.",
    properties: [
      { key: "trust_level", val: "untrusted" },
      { key: "boundary", val: "external" },
      { key: "input_type", val: "http_form" },
      { key: "sanitized", val: "false — inputSanitization absent", positive: false },
    ],
    findings: ["FH-001", "FH-006", "FH-011"],
    controls: ["inputSanitization"],
  },
  n1: {
    description: "Orchestrates the hiring pipeline. Delegates to screener, cv parser and scheduler based on application intake.",
    properties: [
      { key: "llm", val: "gpt-4o-mini" },
      { key: "role_type", val: "coordinator" },
      { key: "autonomy_level", val: "full_auto" },
      { key: "guardrails", val: "inputSanitization, delegationScoping" },
    ],
    findings: ["FH-001", "FH-011"],
    controls: ["delegationScoping"],
  },
  n2: {
    description: "Reads ATS data and fetches LinkedIn profiles to evaluate candidates. Delegates to cvParser. No guardrails.",
    properties: [
      { key: "llm", val: "gpt-4o-mini" },
      { key: "capabilities", val: "read, fetchWeb, decide" },
      { key: "autonomy_level", val: "full_auto" },
      { key: "guardrails", val: "[] — EMPTY", positive: false },
    ],
    findings: ["FH-001", "FH-006"],
    controls: ["contentValidation", "leastPrivilege"],
  },
  n3: {
    description: "Parses CV PDF files and extracts structured candidate data including PII.",
    properties: [
      { key: "llm", val: "gpt-4o-mini" },
      { key: "capabilities", val: "extractInformation, read" },
      { key: "autonomy_level", val: "full_auto" },
      { key: "guardrails", val: "[]" },
    ],
    findings: [],
    controls: ["piiRedaction"],
  },
  n4: {
    description: "Schedules interviews by writing directly to Hiring Calendars. Side effect is irreversible without HITL.",
    properties: [
      { key: "llm", val: "gpt-4o-mini" },
      { key: "capabilities", val: "invokeTools, modify" },
      { key: "autonomy_level", val: "full_auto" },
      { key: "side_effect", val: "true", positive: false },
      { key: "side_effect_reversible", val: "false", positive: false },
    ],
    findings: ["FH-011"],
    controls: ["humanInTheLoop", "dryRunFirst"],
  },
  n5: {
    description: "Sends emails to candidates. Has direct access to GmailSend with no approval gate.",
    properties: [
      { key: "llm", val: "gpt-4o-mini" },
      { key: "capabilities", val: "send" },
      { key: "autonomy_level", val: "full_auto" },
      { key: "requires_approval", val: "false — MISSING HITL", positive: false },
    ],
    findings: ["FH-001", "FH-013"],
    controls: ["humanInTheLoop", "outputFiltering", "piiRedaction"],
  },
  n7: {
    description: "Queries the ATS (Applicant Tracking System) database. Reads high-sensitivity PII data.",
    properties: [
      { key: "capability", val: "read" },
      { key: "target_boundary", val: "internal" },
      { key: "access_kind", val: "db_query" },
      { key: "audit_logging_enabled", val: "false", positive: false },
    ],
    findings: ["FH-001", "FH-002"],
    controls: ["leastPrivilege", "accessScopeRestriction"],
  },
  n8: {
    description: "Fetches external LinkedIn profiles. Content is untrusted and may carry prompt injection payloads.",
    properties: [
      { key: "capability", val: "fetchWeb" },
      { key: "target_boundary", val: "external" },
      { key: "access_kind", val: "external_fetch" },
      { key: "side_effect", val: "false", positive: true },
      { key: "url_allowlist", val: "false", positive: false },
    ],
    findings: ["FH-006"],
    controls: ["contentValidation", "urlAllowlist"],
  },
  n9: {
    description: "Writes entries to Hiring Calendars. Irreversible side effect, no approval required.",
    properties: [
      { key: "capability", val: "modifyResource" },
      { key: "side_effect", val: "true", positive: false },
      { key: "side_effect_reversible", val: "false", positive: false },
      { key: "requires_approval", val: "false", positive: false },
    ],
    findings: ["FH-011"],
    controls: ["humanInTheLoop", "dryRunFirst", "rollbackReady"],
  },
  n10: {
    description: "Sends emails via Gmail API to external recipients. No human-in-the-loop gate.",
    properties: [
      { key: "capability", val: "send" },
      { key: "target_boundary", val: "external" },
      { key: "access_kind", val: "external_send" },
      { key: "side_effect", val: "true", positive: false },
      { key: "side_effect_reversible", val: "false", positive: false },
      { key: "requires_approval", val: "false", positive: false },
    ],
    findings: ["FH-001", "FH-013"],
    controls: ["humanInTheLoop", "domainAllowlist", "outputFiltering"],
  },
  n11: {
    description: "Stores uploaded CV files with PII (names, contact info, work history).",
    properties: [
      { key: "sensitivity", val: "HIGH" },
      { key: "contains_pii", val: "true", positive: false },
      { key: "boundary", val: "internal" },
      { key: "data_classification", val: "confidential" },
    ],
    findings: ["FH-002"],
    controls: ["leastPrivilege", "dataClassification"],
  },
  n12: {
    description: "Primary ATS database. Contains complete candidate records with GDPR-regulated PII.",
    properties: [
      { key: "sensitivity", val: "HIGH · GDPR" },
      { key: "contains_pii", val: "true", positive: false },
      { key: "gdpr_regulated", val: "true", positive: false },
      { key: "boundary", val: "internal" },
    ],
    findings: ["FH-001", "FH-002"],
    controls: ["leastPrivilege", "accessScopeRestriction", "dataClassification"],
  },
  n13: {
    description: "External LinkedIn profiles fetched at runtime. Content is untrusted, may include injection payloads.",
    properties: [
      { key: "sensitivity", val: "MEDIUM" },
      { key: "boundary", val: "external" },
      { key: "trust_level", val: "untrusted" },
      { key: "content_validated", val: "false", positive: false },
    ],
    findings: ["FH-006"],
    controls: ["contentValidation", "urlAllowlist"],
  },
  n14: {
    description: "Internal hiring calendar. Entries are irreversible once written.",
    properties: [
      { key: "sensitivity", val: "MEDIUM" },
      { key: "boundary", val: "internal" },
      { key: "write_validated", val: "false", positive: false },
    ],
    findings: ["FH-011"],
    controls: ["humanInTheLoop", "rollbackReady"],
  },
  n15: {
    description: "Outbound email to candidate. External boundary, no content filtering or approval gate.",
    properties: [
      { key: "boundary", val: "external" },
      { key: "approval_gate_present", val: "false", positive: false },
      { key: "content_filtered", val: "false", positive: false },
    ],
    findings: ["FH-001", "FH-003"],
    controls: ["humanInTheLoop", "outputFiltering"],
  },
  c3: {
    description: "Human approval gate on GmailSend. Currently ABSENT — emails sent automatically without review.",
    properties: [
      { key: "status", val: "absent — CRITICAL GAP", positive: false },
      { key: "breaks_capabilities", val: "send, modifyResource, deleteResource" },
      { key: "effect", val: "total block" },
      { key: "cost_estimate", val: "low" },
    ],
    findings: ["FH-001", "FH-003", "FH-013"],
    controls: [],
  },
  c4: {
    description: "Content validation on LinkedInFetch. Currently ABSENT — untrusted web content flows to agents without sanitization.",
    properties: [
      { key: "status", val: "absent — CRITICAL GAP", positive: false },
      { key: "breaks_capabilities", val: "fetchWeb" },
      { key: "effect", val: "partial mitigation" },
      { key: "cost_estimate", val: "low" },
    ],
    findings: ["FH-006"],
    controls: [],
  },
};
